/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include<stdio.h>
#include<stdint.h>
#include"main.h"
#include"led.h"

typedef struct
{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void (*task_handler)(void);
}TCB_t;

TCB_t user_task[MAX_TASKS];

uint8_t current_task = 1; //task 1 is running
uint32_t g_tick_count = 0;

__attribute((naked)) void init_scheduler_stack(uint32_t sched_top_stack);
__attribute__((naked)) void switch_sp_psp(void);

void init_tasks_stacks(void);
void init_systic_timer(uint32_t tick_hz);
void enable_processor_faults(void);
void  update_next_task(void);
void save_psp_value(uint32_t current_psp_value);
void task_delay(uint32_t tick_count);
void  unblock_tasks();
void update_global_tick_count();
void schedule(void);


uint32_t get_psp_value(void);

void idle_task(void);
void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);


int main(void)
{
	enable_processor_faults();

	init_scheduler_stack(SCHED_STACK_START);

	init_tasks_stacks();

	led_init_all();

	init_systic_timer(TICK_HZ);

	switch_sp_psp();

	task1_handler();

	for(;;);
}

void enable_processor_faults(void)
{
	uint32_t* pSHCSR = (uint32_t*)0xE000ED24;
		*pSHCSR |= (1 << 16 ); //mem_manage
		*pSHCSR |= (1 << 17 ); // busfault
  *pSHCSR |= (1 << 18 ); // usagefault
}


void HardFault_Handler(void)
{
	printf("Execption :  HardFault_Handler \n");
	while(1);

}


void MemManage_Handler(void)
  {
	printf("Execption :  MemManage_Handler \n");
		while(1);
  }


void BusFault_Handler(void)
  {
	printf("Execption :  BusFault_Handler \n");
		while(1);
  }

void UsageFault_Handler(void)
{
	printf("Exception : usagefault");
	while(1);
}


void idle_task(void)
{
	while(1);
}

void task1_handler(void)
{
	while(1)
	{
		led_on(LED_GREEN);
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
	}
}

void task2_handler(void)
{
	while(1)
	{
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);
	}
}

void task3_handler(void)
{
	while(1)
	{
		led_on(LED_RED);
		task_delay(250);
		led_off(LED_RED);
		task_delay(250);
	}
}

void task4_handler(void)
{
	while(1)
	{
		led_on(LED_BLUE);
		task_delay(125);
		led_off(LED_BLUE);
		task_delay(125);
	}
}

void init_systic_timer(uint32_t tick_hz)
{
	uint32_t count_value = SYSTEM_TICK_CLK / tick_hz;
	count_value -= 1;
	uint32_t* pSRVR = (uint32_t*)0xE000E014;
	uint32_t* pSCSR = (uint32_t*)0xE000E010;


	//clear the value of srvr
	*pSRVR &= ~(0x00FFFFFF);
	//load the value of srvr
	*pSRVR |= count_value;

	//setting the systick control and status register
	*pSCSR |= (1 << 1); // enable the systect exception;
	*pSCSR |= (1 << 2); //enable the clock 16 mz internal rc oscillator

	//enable the counter
	*pSCSR |= (1 << 0) ;


}

__attribute((naked)) void init_scheduler_stack(uint32_t sched_top_stack)
{
	__asm volatile ("MSR MSP , %0": :"r"(sched_top_stack));
	__asm volatile ("BX LR");

}


void init_tasks_stacks(void)
{
	uint32_t* pPSP;
	user_task[0].current_state = TASK_RUNNING_STATE;
	user_task[1].current_state = TASK_RUNNING_STATE;
	user_task[2].current_state = TASK_RUNNING_STATE;
	user_task[3].current_state = TASK_RUNNING_STATE;
	user_task[4].current_state = TASK_RUNNING_STATE;


	user_task[0].psp_value  = IDLE_STACK_START;
	user_task[1].psp_value  = T1_STACK_START;
	user_task[2].psp_value  = T2_STACK_START;
	user_task[3].psp_value  = T3_STACK_START;
	user_task[4].psp_value  = T4_STACK_START;

	user_task[0].task_handler  = &idle_task;
	user_task[1].task_handler  = &task1_handler;
	user_task[2].task_handler  = &task2_handler;
	user_task[3].task_handler  = &task3_handler;
	user_task[4].task_handler  = &task4_handler;


	for(int i = 0 ; i < MAX_TASKS ; i++)
	{
		pPSP = (uint32_t*)user_task[i].psp_value;
		pPSP--;
		*pPSP = DUMMY_XPSR;
		pPSP--;
		*pPSP =(uint32_t) user_task[i].task_handler;
		pPSP--;
		*pPSP = 0xFFFFFFFD;
		for(int j = 0 ; j < 13 ;j++)
		{
			pPSP--;
			*pPSP = 0 ;
		}

		user_task[i].psp_value =(uint32_t) pPSP;

	}
}


uint32_t get_psp_value(void)
{
	return user_task[current_task].psp_value ;
}
__attribute((naked)) void switch_sp_psp(void)
{
	//1/ initialze th psp with ths task 1 stack
	__asm volatile("PUSH {LR} ");
	__asm volatile("BL get_psp_value");
	__asm volatile ("MSR PSP , R0");
	__asm volatile("POP {LR}");

	// 2. change sp to psp
	__asm volatile ("MOV R0, #0x02");
	__asm volatile ("MSR CONTROL ,R0");
	__asm volatile ("BX LR");

}


__attribute((naked))void PendSV_Handler(void)
{
	 __asm volatile ("MRS R0 ,PSP");
	  __asm volatile ("STMDB R0!, {R4-R11}");
	  __asm volatile("PUSH {LR}");
	  __asm volatile("BL save_psp_value");


	  __asm volatile("BL update_next_task");
	  __asm volatile("BL get_psp_value");
	  __asm volatile("LDMIA R0!,{R4-R11}");
	  __asm volatile("MSR PSP, R0");
	  __asm volatile("POP {LR}");
	  __asm volatile("BX LR");

}


void SysTick_Handler(void)
{
  uint32_t *pICSR = (uint32_t*)0xE000ED04;
	update_global_tick_count();
  unblock_tasks();
  *pICSR |= (1 << 28);

}
void save_psp_value(uint32_t current_psp_value)
{
	user_task[current_task].psp_value = current_psp_value;

}

void  update_next_task(void)
{
	int state  = TASK_BLOCKED_STATE;
	for(int i = 1 ; i < MAX_TASKS ; i++)
	{
		current_task++;
		current_task %= MAX_TASKS;
		state = user_task[current_task].current_state;
		if((state == TASK_RUNNING_STATE) && (current_task != 0))
		{
			break;
		}
	}

	if(state != TASK_RUNNING_STATE)
	{
		current_task = 0;
	}

}

void task_delay(uint32_t tick_count)
{
	INTERRUPT_DISABLE();

	if(current_task)
	{
	user_task[current_task].block_count = g_tick_count + tick_count;
	user_task[current_task].current_state = TASK_BLOCKED_STATE;
	schedule();
	}


	INTERRUPT_ENABLE();
}

void update_global_tick_count()
{
	g_tick_count++;
}

void  unblock_tasks()
{
	for(int i = 1 ; i < MAX_TASKS ; i++)
	{
		if(user_task[i].current_state != TASK_RUNNING_STATE )
		{
			if(user_task[i].block_count == g_tick_count)
			{
				user_task[i].current_state = TASK_RUNNING_STATE;
			}
		}
	}
}

void schedule(void)
{
	// pendsv
	uint32_t *pICSR = (uint32_t*)0xE000ED04;

	 *pICSR |= (1 << 28);
}
